export let keywords = [
["https://data.geoscience.earth/ncl/geoera/keyword/1315", "oil"],
["https://data.geoscience.earth/ncl/geoera/keyword/757", "sea"],
["https://data.geoscience.earth/ncl/geoera/keyword/2349", "Age"],
["https://data.geoscience.earth/ncl/geoera/keyword/680", "bay"],
["https://data.geoscience.earth/ncl/geoera/keyword/767", "ice"],
["https://data.geoscience.earth/ncl/geoera/keyword/2355", "bed"],
["https://data.geoscience.earth/ncl/geoera/keyword/1159", "ore"],
["https://data.geoscience.earth/ncl/geoera/keyword/2345", "Era"],
["https://data.geoscience.earth/ncl/geoera/keyword/508", "ion"],
["https://data.geoscience.earth/ncl/geoera/keyword/65", "mud"],
["https://data.geoscience.earth/ncl/geoera/keyword/2344", "Eon"],
["https://data.geoscience.earth/ncl/geoera/keyword/681", "bog"],
["https://data.geoscience.earth/ncl/geoera/keyword/1064", "tin"],
["https://data.geoscience.earth/ncl/geoera/keyword/2540", "WFD"],
["https://data.geoscience.earth/ncl/geoera/keyword/413", "IMS"],
["https://data.geoscience.earth/ncl/geoera/keyword/2578", "EOR"],
["https://data.geoscience.earth/ncl/geoera/keyword/2096", "rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1490", "risk"],
["https://data.geoscience.earth/ncl/geoera/keyword/2129", "test"],
["https://data.geoscience.earth/ncl/geoera/keyword/1607", "land"],
["https://data.geoscience.earth/ncl/geoera/keyword/2016", "soil"],
["https://data.geoscience.earth/ncl/geoera/keyword/1006", "lead"],
["https://data.geoscience.earth/ncl/geoera/keyword/1217", "mine"],
["https://data.geoscience.earth/ncl/geoera/keyword/64", "sand"],
["https://data.geoscience.earth/ncl/geoera/keyword/105", "coal"],
["https://data.geoscience.earth/ncl/geoera/keyword/1598", "road"],
["https://data.geoscience.earth/ncl/geoera/keyword/1038", "iron"],
["https://data.geoscience.earth/ncl/geoera/keyword/66", "clay"],
["https://data.geoscience.earth/ncl/geoera/keyword/433", "acid"],
["https://data.geoscience.earth/ncl/geoera/keyword/756", "lake"],
["https://data.geoscience.earth/ncl/geoera/keyword/485", "salt"],
["https://data.geoscience.earth/ncl/geoera/keyword/1010", "gold"],
["https://data.geoscience.earth/ncl/geoera/keyword/688", "pool"],
["https://data.geoscience.earth/ncl/geoera/keyword/67", "silt"],
["https://data.geoscience.earth/ncl/geoera/keyword/76", "peat"],
["https://data.geoscience.earth/ncl/geoera/keyword/691", "cave"],
["https://data.geoscience.earth/ncl/geoera/keyword/742", "tide"],
["https://data.geoscience.earth/ncl/geoera/keyword/1008", "zinc"],
["https://data.geoscience.earth/ncl/geoera/keyword/325", "fold"],
["https://data.geoscience.earth/ncl/geoera/keyword/1442", "hill"],
["https://data.geoscience.earth/ncl/geoera/keyword/308", "vein"],
["https://data.geoscience.earth/ncl/geoera/keyword/1928", "dune"],
["https://data.geoscience.earth/ncl/geoera/keyword/678", "gulf"],
["https://data.geoscience.earth/ncl/geoera/keyword/1084", "lime"],
["https://data.geoscience.earth/ncl/geoera/keyword/687", "pond"],
["https://data.geoscience.earth/ncl/geoera/keyword/598", "seep"],
["https://data.geoscience.earth/ncl/geoera/keyword/1453", "dump"],
["https://data.geoscience.earth/ncl/geoera/keyword/914", "mica"],
["https://data.geoscience.earth/ncl/geoera/keyword/686", "moor"],
["https://data.geoscience.earth/ncl/geoera/keyword/71", "marl"],
["https://data.geoscience.earth/ncl/geoera/keyword/982", "onyx"],
["https://data.geoscience.earth/ncl/geoera/keyword/985", "opal"],
["https://data.geoscience.earth/ncl/geoera/keyword/947", "ruby"],
["https://data.geoscience.earth/ncl/geoera/keyword/1595", "water"],
["https://data.geoscience.earth/ncl/geoera/keyword/406", "model"],
["https://data.geoscience.earth/ncl/geoera/keyword/2558", "local"],
["https://data.geoscience.earth/ncl/geoera/keyword/307", "joint"],
["https://data.geoscience.earth/ncl/geoera/keyword/2351", "group"],
["https://data.geoscience.earth/ncl/geoera/keyword/760", "ocean"],
["https://data.geoscience.earth/ncl/geoera/keyword/1161", "waste"],
["https://data.geoscience.earth/ncl/geoera/keyword/467", "metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/389", "sonar"],
["https://data.geoscience.earth/ncl/geoera/keyword/310", "fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/1416", "light"],
["https://data.geoscience.earth/ncl/geoera/keyword/672", "coast"],
["https://data.geoscience.earth/ncl/geoera/keyword/1413", "x-ray"],
["https://data.geoscience.earth/ncl/geoera/keyword/2545", "yield"],
["https://data.geoscience.earth/ncl/geoera/keyword/779", "river"],
["https://data.geoscience.earth/ncl/geoera/keyword/1352", "gases"],
["https://data.geoscience.earth/ncl/geoera/keyword/94", "shale"],
["https://data.geoscience.earth/ncl/geoera/keyword/557", "stone"],
["https://data.geoscience.earth/ncl/geoera/keyword/429", "oxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/716", "flood"],
["https://data.geoscience.earth/ncl/geoera/keyword/2094", "steel"],
["https://data.geoscience.earth/ncl/geoera/keyword/2488", "trend"],
["https://data.geoscience.earth/ncl/geoera/keyword/98", "chalk"],
["https://data.geoscience.earth/ncl/geoera/keyword/1072", "boron"],
["https://data.geoscience.earth/ncl/geoera/keyword/780", "delta"],
["https://data.geoscience.earth/ncl/geoera/keyword/679", "creek"],
["https://data.geoscience.earth/ncl/geoera/keyword/739", "swell"],
["https://data.geoscience.earth/ncl/geoera/keyword/660", "plain"],
["https://data.geoscience.earth/ncl/geoera/keyword/510", "anion"],
["https://data.geoscience.earth/ncl/geoera/keyword/124", "slate"],
["https://data.geoscience.earth/ncl/geoera/keyword/2348", "Epoch"],
["https://data.geoscience.earth/ncl/geoera/keyword/468", "mafic"],
["https://data.geoscience.earth/ncl/geoera/keyword/684", "marsh"],
["https://data.geoscience.earth/ncl/geoera/keyword/677", "cliff"],
["https://data.geoscience.earth/ncl/geoera/keyword/1158", "brick"],
["https://data.geoscience.earth/ncl/geoera/keyword/1391", "fires"],
["https://data.geoscience.earth/ncl/geoera/keyword/1089", "ochre"],
["https://data.geoscience.earth/ncl/geoera/keyword/2092", "alloy"],
["https://data.geoscience.earth/ncl/geoera/keyword/936", "amber"],
["https://data.geoscience.earth/ncl/geoera/keyword/139", "skarn"],
["https://data.geoscience.earth/ncl/geoera/keyword/682", "swamp"],
["https://data.geoscience.earth/ncl/geoera/keyword/654", "energy"],
["https://data.geoscience.earth/ncl/geoera/keyword/1520", "impact"],
["https://data.geoscience.earth/ncl/geoera/keyword/2557", "global"],
["https://data.geoscience.earth/ncl/geoera/keyword/2463", "policy"],
["https://data.geoscience.earth/ncl/geoera/keyword/1476", "social"],
["https://data.geoscience.earth/ncl/geoera/keyword/535", "sample"],
["https://data.geoscience.earth/ncl/geoera/keyword/1253", "mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/2107", "method"],
["https://data.geoscience.earth/ncl/geoera/keyword/2346", "Period"],
["https://data.geoscience.earth/ncl/geoera/keyword/1358", "hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/1597", "supply"],
["https://data.geoscience.earth/ncl/geoera/keyword/1455", "active"],
["https://data.geoscience.earth/ncl/geoera/keyword/2354", "member"],
["https://data.geoscience.earth/ncl/geoera/keyword/2099", "fossil"],
["https://data.geoscience.earth/ncl/geoera/keyword/1477", "people"],
["https://data.geoscience.earth/ncl/geoera/keyword/2494", "review"],
["https://data.geoscience.earth/ncl/geoera/keyword/2112", "dating"],
["https://data.geoscience.earth/ncl/geoera/keyword/63", "gravel"],
["https://data.geoscience.earth/ncl/geoera/keyword/1004", "copper"],
["https://data.geoscience.earth/ncl/geoera/keyword/1007", "nickel"],
["https://data.geoscience.earth/ncl/geoera/keyword/596", "spring"],
["https://data.geoscience.earth/ncl/geoera/keyword/1005", "cobalt"],
["https://data.geoscience.earth/ncl/geoera/keyword/2595", "basins"],
["https://data.geoscience.earth/ncl/geoera/keyword/1148", "cement"],
["https://data.geoscience.earth/ncl/geoera/keyword/666", "valley"],
["https://data.geoscience.earth/ncl/geoera/keyword/1218", "quarry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1857", "Alpine"],
["https://data.geoscience.earth/ncl/geoera/keyword/2213", "Eocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/31", "basalt"],
["https://data.geoscience.earth/ncl/geoera/keyword/112", "gypsum"],
["https://data.geoscience.earth/ncl/geoera/keyword/918", "pyrite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1011", "silver"],
["https://data.geoscience.earth/ncl/geoera/keyword/2364", "tephra"],
["https://data.geoscience.earth/ncl/geoera/keyword/919", "quartz"],
["https://data.geoscience.earth/ncl/geoera/keyword/934", "zircon"],
["https://data.geoscience.earth/ncl/geoera/keyword/1997", "graben"],
["https://data.geoscience.earth/ncl/geoera/keyword/509", "cation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1050", "indium"],
["https://data.geoscience.earth/ncl/geoera/keyword/5", "gabbro"],
["https://data.geoscience.earth/ncl/geoera/keyword/924", "silica"],
["https://data.geoscience.earth/ncl/geoera/keyword/119", "gneiss"],
["https://data.geoscience.earth/ncl/geoera/keyword/2561", "helium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2520", "patent"],
["https://data.geoscience.earth/ncl/geoera/keyword/1101", "placer"],
["https://data.geoscience.earth/ncl/geoera/keyword/864", "pumice"],
["https://data.geoscience.earth/ncl/geoera/keyword/725", "runoff"],
["https://data.geoscience.earth/ncl/geoera/keyword/1044", "barium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1874", "desert"],
["https://data.geoscience.earth/ncl/geoera/keyword/2445", "tremor"],
["https://data.geoscience.earth/ncl/geoera/keyword/883", "baryte"],
["https://data.geoscience.earth/ncl/geoera/keyword/905", "garnet"],
["https://data.geoscience.earth/ncl/geoera/keyword/746", "inflow"],
["https://data.geoscience.earth/ncl/geoera/keyword/80", "sludge"],
["https://data.geoscience.earth/ncl/geoera/keyword/1047", "cesium"],
["https://data.geoscience.earth/ncl/geoera/keyword/160", "lithic"],
["https://data.geoscience.earth/ncl/geoera/keyword/920", "rutile"],
["https://data.geoscience.earth/ncl/geoera/keyword/2182", "Tonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/2073", "botany"],
["https://data.geoscience.earth/ncl/geoera/keyword/667", "canyon"],
["https://data.geoscience.earth/ncl/geoera/keyword/1031", "cerium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1077", "iodine"],
["https://data.geoscience.earth/ncl/geoera/keyword/458", "potash"],
["https://data.geoscience.earth/ncl/geoera/keyword/2369", "aplite"],
["https://data.geoscience.earth/ncl/geoera/keyword/884", "borate"],
["https://data.geoscience.earth/ncl/geoera/keyword/23", "dacite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1021", "erbium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1160", "gangue"],
["https://data.geoscience.earth/ncl/geoera/keyword/2160", "Hadean"],
["https://data.geoscience.earth/ncl/geoera/keyword/892", "kaolin"],
["https://data.geoscience.earth/ncl/geoera/keyword/27", "latite"],
["https://data.geoscience.earth/ncl/geoera/keyword/132", "marble"],
["https://data.geoscience.earth/ncl/geoera/keyword/1014", "osmium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1057", "radium"],
["https://data.geoscience.earth/ncl/geoera/keyword/925", "spinel"],
["https://data.geoscience.earth/ncl/geoera/keyword/2317", "Visean"],
["https://data.geoscience.earth/ncl/geoera/keyword/820", "network"],
["https://data.geoscience.earth/ncl/geoera/keyword/1451", "climate"],
["https://data.geoscience.earth/ncl/geoera/keyword/2095", "mineral"],
["https://data.geoscience.earth/ncl/geoera/keyword/1691", "mapping"],
["https://data.geoscience.earth/ncl/geoera/keyword/568", "aquifer"],
["https://data.geoscience.earth/ncl/geoera/keyword/1165", "primary"],
["https://data.geoscience.earth/ncl/geoera/keyword/1117", "organic"],
["https://data.geoscience.earth/ncl/geoera/keyword/511", "isotope"],
["https://data.geoscience.earth/ncl/geoera/keyword/191", "erosion"],
["https://data.geoscience.earth/ncl/geoera/keyword/255", "contact"],
["https://data.geoscience.earth/ncl/geoera/keyword/2491", "ecology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1437", "leakage"],
["https://data.geoscience.earth/ncl/geoera/keyword/1891", "volcano"],
["https://data.geoscience.earth/ncl/geoera/keyword/2449", "pathway"],
["https://data.geoscience.earth/ncl/geoera/keyword/781", "estuary"],
["https://data.geoscience.earth/ncl/geoera/keyword/2453", "farming"],
["https://data.geoscience.earth/ncl/geoera/keyword/851", "granite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1961", "sea bed"],
["https://data.geoscience.earth/ncl/geoera/keyword/1066", "uranium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1074", "silicon"],
["https://data.geoscience.earth/ncl/geoera/keyword/2215", "Miocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/1071", "arsenic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1076", "sulphur"],
["https://data.geoscience.earth/ncl/geoera/keyword/1387", "drought"],
["https://data.geoscience.earth/ncl/geoera/keyword/1051", "lithium"],
["https://data.geoscience.earth/ncl/geoera/keyword/209", "melting"],
["https://data.geoscience.earth/ncl/geoera/keyword/484", "nitrate"],
["https://data.geoscience.earth/ncl/geoera/keyword/917", "olivine"],
["https://data.geoscience.earth/ncl/geoera/keyword/899", "diamond"],
["https://data.geoscience.earth/ncl/geoera/keyword/1264", "sorting"],
["https://data.geoscience.earth/ncl/geoera/keyword/2047", "topsoil"],
["https://data.geoscience.earth/ncl/geoera/keyword/1611", "reserve"],
["https://data.geoscience.earth/ncl/geoera/keyword/745", "Archean"],
["https://data.geoscience.earth/ncl/geoera/keyword/689", "glacier"],
["https://data.geoscience.earth/ncl/geoera/keyword/2543", "tourism"],
["https://data.geoscience.earth/ncl/geoera/keyword/1283", "burning"],
["https://data.geoscience.earth/ncl/geoera/keyword/1046", "cadmium"],
["https://data.geoscience.earth/ncl/geoera/keyword/885", "calcite"],
["https://data.geoscience.earth/ncl/geoera/keyword/498", "sulfide"],
["https://data.geoscience.earth/ncl/geoera/keyword/1063", "thorium"],
["https://data.geoscience.earth/ncl/geoera/keyword/430", "ammonia"],
["https://data.geoscience.earth/ncl/geoera/keyword/228", "folding"],
["https://data.geoscience.earth/ncl/geoera/keyword/876", "apatite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2172", "Permian"],
["https://data.geoscience.earth/ncl/geoera/keyword/2033", "subsoil"],
["https://data.geoscience.earth/ncl/geoera/keyword/1379", "tsunami"],
["https://data.geoscience.earth/ncl/geoera/keyword/106", "lignite"],
["https://data.geoscience.earth/ncl/geoera/keyword/673", "wetland"],
["https://data.geoscience.earth/ncl/geoera/keyword/1079", "bromine"],
["https://data.geoscience.earth/ncl/geoera/keyword/1048", "gallium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1053", "mercury"],
["https://data.geoscience.earth/ncl/geoera/keyword/2177", "Neogene"],
["https://data.geoscience.earth/ncl/geoera/keyword/1055", "niobium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1058", "rhenium"],
["https://data.geoscience.earth/ncl/geoera/keyword/431", "silicic"],
["https://data.geoscience.earth/ncl/geoera/keyword/472", "sulfate"],
["https://data.geoscience.earth/ncl/geoera/keyword/1028", "yttrium"],
["https://data.geoscience.earth/ncl/geoera/keyword/933", "zeolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1086", "alumina"],
["https://data.geoscience.earth/ncl/geoera/keyword/1314", "asphalt"],
["https://data.geoscience.earth/ncl/geoera/keyword/143", "bauxite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1045", "bismuth"],
["https://data.geoscience.earth/ncl/geoera/keyword/483", "nitrite"],
["https://data.geoscience.earth/ncl/geoera/keyword/861", "perlite"],
["https://data.geoscience.earth/ncl/geoera/keyword/940", "emerald"],
["https://data.geoscience.earth/ncl/geoera/keyword/1049", "hafnium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1889", "iceberg"],
["https://data.geoscience.earth/ncl/geoera/keyword/1486", "injured"],
["https://data.geoscience.earth/ncl/geoera/keyword/219", "rifting"],
["https://data.geoscience.earth/ncl/geoera/keyword/2597", "shields"],
["https://data.geoscience.earth/ncl/geoera/keyword/902", "sylvite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1026", "terbium"],
["https://data.geoscience.earth/ncl/geoera/keyword/85", "breccia"],
["https://data.geoscience.earth/ncl/geoera/keyword/141", "greisen"],
["https://data.geoscience.earth/ncl/geoera/keyword/1024", "holmium"],
["https://data.geoscience.earth/ncl/geoera/keyword/171", "pelitic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2377", "syenite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1027", "thulium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2135", "analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/2560", "regional"],
["https://data.geoscience.earth/ncl/geoera/keyword/536", "borehole"],
["https://data.geoscience.earth/ncl/geoera/keyword/1695", "sampling"],
["https://data.geoscience.earth/ncl/geoera/keyword/1471", "economic"],
["https://data.geoscience.earth/ncl/geoera/keyword/60", "sediment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1299", "resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/1766", "capacity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2550", "strategy"],
["https://data.geoscience.earth/ncl/geoera/keyword/1716", "software"],
["https://data.geoscience.earth/ncl/geoera/keyword/2149", "standard"],
["https://data.geoscience.earth/ncl/geoera/keyword/2496", "baseline"],
["https://data.geoscience.earth/ncl/geoera/keyword/1727", "metadata"],
["https://data.geoscience.earth/ncl/geoera/keyword/618", "recharge"],
["https://data.geoscience.earth/ncl/geoera/keyword/1601", "land use"],
["https://data.geoscience.earth/ncl/geoera/keyword/1479", "heritage"],
["https://data.geoscience.earth/ncl/geoera/keyword/2526", "porosity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2529", "rainfall"],
["https://data.geoscience.earth/ncl/geoera/keyword/1472", "property"],
["https://data.geoscience.earth/ncl/geoera/keyword/1149", "concrete"],
["https://data.geoscience.earth/ncl/geoera/keyword/2174", "Jurassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/583", "seasonal"],
["https://data.geoscience.earth/ncl/geoera/keyword/726", "drainage"],
["https://data.geoscience.earth/ncl/geoera/keyword/604", "disposal"],
["https://data.geoscience.earth/ncl/geoera/keyword/206", "eruption"],
["https://data.geoscience.earth/ncl/geoera/keyword/306", "fracture"],
["https://data.geoscience.earth/ncl/geoera/keyword/2163", "Cenozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2218", "Holocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/1356", "disaster"],
["https://data.geoscience.earth/ncl/geoera/keyword/1539", "forestry"],
["https://data.geoscience.earth/ncl/geoera/keyword/647", "isolated"],
["https://data.geoscience.earth/ncl/geoera/keyword/227", "faulting"],
["https://data.geoscience.earth/ncl/geoera/keyword/1015", "platinum"],
["https://data.geoscience.earth/ncl/geoera/keyword/2173", "Triassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/435", "chloride"],
["https://data.geoscience.earth/ncl/geoera/keyword/1037", "chromium"],
["https://data.geoscience.earth/ncl/geoera/keyword/720", "flooding"],
["https://data.geoscience.earth/ncl/geoera/keyword/1277", "leaching"],
["https://data.geoscience.earth/ncl/geoera/keyword/2216", "Pliocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/1444", "mountain"],
["https://data.geoscience.earth/ncl/geoera/keyword/2532", "scarcity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2162", "Mesozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1040", "titanium"],
["https://data.geoscience.earth/ncl/geoera/keyword/96", "dolomite"],
["https://data.geoscience.earth/ncl/geoera/keyword/859", "laterite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1747", "workflow"],
["https://data.geoscience.earth/ncl/geoera/keyword/759", "deep sea"],
["https://data.geoscience.earth/ncl/geoera/keyword/2170", "Devonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/91", "mudstone"],
["https://data.geoscience.earth/ncl/geoera/keyword/1041", "vanadium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2452", "landfill"],
["https://data.geoscience.earth/ncl/geoera/keyword/44", "porphyry"],
["https://data.geoscience.earth/ncl/geoera/keyword/907", "graphite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1078", "selenium"],
["https://data.geoscience.earth/ncl/geoera/keyword/440", "ammonium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2167", "Cambrian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1080", "fluorine"],
["https://data.geoscience.earth/ncl/geoera/keyword/908", "hematite"],
["https://data.geoscience.earth/ncl/geoera/keyword/544", "pH value"],
["https://data.geoscience.earth/ncl/geoera/keyword/1061", "tantalum"],
["https://data.geoscience.earth/ncl/geoera/keyword/29", "andesite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1070", "antimony"],
["https://data.geoscience.earth/ncl/geoera/keyword/2049", "geogenic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1456", "inactive"],
["https://data.geoscience.earth/ncl/geoera/keyword/2169", "Silurian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1422", "adaption"],
["https://data.geoscience.earth/ncl/geoera/keyword/846", "iron ore"],
["https://data.geoscience.earth/ncl/geoera/keyword/1059", "rubidium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1036", "samarium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1065", "tungsten"],
["https://data.geoscience.earth/ncl/geoera/keyword/887", "chromite"],
["https://data.geoscience.earth/ncl/geoera/keyword/903", "feldspar"],
["https://data.geoscience.earth/ncl/geoera/keyword/913", "ilmenite"],
["https://data.geoscience.earth/ncl/geoera/keyword/20", "rhyolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/77", "sapropel"],
["https://data.geoscience.earth/ncl/geoera/keyword/2324", "Silesian"],
["https://data.geoscience.earth/ncl/geoera/keyword/25", "trachyte"],
["https://data.geoscience.earth/ncl/geoera/keyword/295", "cleavage"],
["https://data.geoscience.earth/ncl/geoera/keyword/43", "dolerite"],
["https://data.geoscience.earth/ncl/geoera/keyword/904", "fluorite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2577", "Fracking"],
["https://data.geoscience.earth/ncl/geoera/keyword/733", "low flow"],
["https://data.geoscience.earth/ncl/geoera/keyword/1091", "magnesia"],
["https://data.geoscience.earth/ncl/geoera/keyword/916", "monazite"],
["https://data.geoscience.earth/ncl/geoera/keyword/948", "sapphire"],
["https://data.geoscience.earth/ncl/geoera/keyword/1068", "scandium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1853", "Variscan"],
["https://data.geoscience.earth/ncl/geoera/keyword/971", "amethyst"],
["https://data.geoscience.earth/ncl/geoera/keyword/134", "eclogite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1022", "europium"],
["https://data.geoscience.earth/ncl/geoera/keyword/935", "gemstone"],
["https://data.geoscience.earth/ncl/geoera/keyword/303", "layering"],
["https://data.geoscience.earth/ncl/geoera/keyword/1025", "lutetium"],
["https://data.geoscience.earth/ncl/geoera/keyword/150", "mylonite"],
["https://data.geoscience.earth/ncl/geoera/keyword/966", "obsidian"],
["https://data.geoscience.earth/ncl/geoera/keyword/758", "open sea"],
["https://data.geoscience.earth/ncl/geoera/keyword/1220", "sand pit"],
["https://data.geoscience.earth/ncl/geoera/keyword/922", "sericite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2352", "subgroup"],
["https://data.geoscience.earth/ncl/geoera/keyword/1062", "thallium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2275", "Toarcian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1825", "modelling"],
["https://data.geoscience.earth/ncl/geoera/keyword/1478", "community"],
["https://data.geoscience.earth/ncl/geoera/keyword/2455", "ecosystem"],
["https://data.geoscience.earth/ncl/geoera/keyword/2098", "evolution"],
["https://data.geoscience.earth/ncl/geoera/keyword/2353", "formation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1357", "pollution"],
["https://data.geoscience.earth/ncl/geoera/keyword/1617", "landscape"],
["https://data.geoscience.earth/ncl/geoera/keyword/451", "carbonate"],
["https://data.geoscience.earth/ncl/geoera/keyword/1166", "secondary"],
["https://data.geoscience.earth/ncl/geoera/keyword/2576", "injection"],
["https://data.geoscience.earth/ncl/geoera/keyword/1138", "recycling"],
["https://data.geoscience.earth/ncl/geoera/keyword/2065", "tectonics"],
["https://data.geoscience.earth/ncl/geoera/keyword/86", "sandstone"],
["https://data.geoscience.earth/ncl/geoera/keyword/1127", "chemicals"],
["https://data.geoscience.earth/ncl/geoera/keyword/1377", "landslide"],
["https://data.geoscience.earth/ncl/geoera/keyword/837", "aggregate"],
["https://data.geoscience.earth/ncl/geoera/keyword/97", "limestone"],
["https://data.geoscience.earth/ncl/geoera/keyword/1405", "radiation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2121", "measuring"],
["https://data.geoscience.earth/ncl/geoera/keyword/1321", "petroleum"],
["https://data.geoscience.earth/ncl/geoera/keyword/740", "sea level"],
["https://data.geoscience.earth/ncl/geoera/keyword/2079", "hydrology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2029", "soil type"],
["https://data.geoscience.earth/ncl/geoera/keyword/424", "anomalies"],
["https://data.geoscience.earth/ncl/geoera/keyword/834", "commodity"],
["https://data.geoscience.earth/ncl/geoera/keyword/222", "spreading"],
["https://data.geoscience.earth/ncl/geoera/keyword/2502", "corrosion"],
["https://data.geoscience.earth/ncl/geoera/keyword/205", "volcanism"],
["https://data.geoscience.earth/ncl/geoera/keyword/234", "oxidation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2161", "Paleozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/216", "accretion"],
["https://data.geoscience.earth/ncl/geoera/keyword/1060", "strontium"],
["https://data.geoscience.earth/ncl/geoera/keyword/207", "intrusion"],
["https://data.geoscience.earth/ncl/geoera/keyword/1052", "magnesium"],
["https://data.geoscience.earth/ncl/geoera/keyword/493", "phosphate"],
["https://data.geoscience.earth/ncl/geoera/keyword/1241", "quarrying"],
["https://data.geoscience.earth/ncl/geoera/keyword/2097", "biosphere"],
["https://data.geoscience.earth/ncl/geoera/keyword/1709", "data base"],
["https://data.geoscience.earth/ncl/geoera/keyword/2184", "Ediacaran"],
["https://data.geoscience.earth/ncl/geoera/keyword/1974", "continent"],
["https://data.geoscience.earth/ncl/geoera/keyword/1039", "manganese"],
["https://data.geoscience.earth/ncl/geoera/keyword/1675", "pollutant"],
["https://data.geoscience.earth/ncl/geoera/keyword/2051", "geography"],
["https://data.geoscience.earth/ncl/geoera/keyword/1162", "host rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1033", "neodymium"],
["https://data.geoscience.earth/ncl/geoera/keyword/772", "sea water"],
["https://data.geoscience.earth/ncl/geoera/keyword/1075", "tellurium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2331", "Sarmatian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1558", "utilities"],
["https://data.geoscience.earth/ncl/geoera/keyword/1042", "aluminium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2510", "indicator"],
["https://data.geoscience.earth/ncl/geoera/keyword/1056", "potassium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2516", "noble gas"],
["https://data.geoscience.earth/ncl/geoera/keyword/2176", "Paleogene"],
["https://data.geoscience.earth/ncl/geoera/keyword/1417", "microwave"],
["https://data.geoscience.earth/ncl/geoera/keyword/2323", "Dinantian"],
["https://data.geoscience.earth/ncl/geoera/keyword/912", "magnetite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1108", "pegmatite"],
["https://data.geoscience.earth/ncl/geoera/keyword/113", "anhydrite"],
["https://data.geoscience.earth/ncl/geoera/keyword/281", "foliation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1073", "germanium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2212", "Paleocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/2332", "Pannonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/93", "siltstone"],
["https://data.geoscience.earth/ncl/geoera/keyword/896", "bentonite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1754", "end point"],
["https://data.geoscience.earth/ncl/geoera/keyword/110", "evaporite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1294", "flotation"],
["https://data.geoscience.earth/ncl/geoera/keyword/233", "hydration"],
["https://data.geoscience.earth/ncl/geoera/keyword/1313", "oil shale"],
["https://data.geoscience.earth/ncl/geoera/keyword/2214", "Oligocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/2524", "pesticide"],
["https://data.geoscience.earth/ncl/geoera/keyword/664", "river bed"],
["https://data.geoscience.earth/ncl/geoera/keyword/1067", "zirconium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2164", "Eoarchean"],
["https://data.geoscience.earth/ncl/geoera/keyword/1032", "lanthanum"],
["https://data.geoscience.earth/ncl/geoera/keyword/1929", "sand dune"],
["https://data.geoscience.earth/ncl/geoera/keyword/2123", "telemetry"],
["https://data.geoscience.earth/ncl/geoera/keyword/698", "watershed"],
["https://data.geoscience.earth/ncl/geoera/keyword/1043", "beryllium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1281", "calcining"],
["https://data.geoscience.earth/ncl/geoera/keyword/2293", "Campanian"],
["https://data.geoscience.earth/ncl/geoera/keyword/983", "carnelian"],
["https://data.geoscience.earth/ncl/geoera/keyword/92", "claystone"],
["https://data.geoscience.earth/ncl/geoera/keyword/456", "dolomitic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2459", "ecoregion"],
["https://data.geoscience.earth/ncl/geoera/keyword/133", "granulite"],
["https://data.geoscience.earth/ncl/geoera/keyword/586", "hot water"],
["https://data.geoscience.earth/ncl/geoera/keyword/910", "leucoxene"],
["https://data.geoscience.earth/ncl/geoera/keyword/250", "lineation"],
["https://data.geoscience.earth/ncl/geoera/keyword/911", "magnesite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2309", "Messinian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1069", "metalloid"],
["https://data.geoscience.earth/ncl/geoera/keyword/135", "migmatite"],
["https://data.geoscience.earth/ncl/geoera/keyword/477", "non-metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/1018", "palladium"],
["https://data.geoscience.earth/ncl/geoera/keyword/580", "perennial"],
["https://data.geoscience.earth/ncl/geoera/keyword/35", "phonolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/111", "rock salt"],
["https://data.geoscience.earth/ncl/geoera/keyword/889", "sepiolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/989", "spodumene"],
["https://data.geoscience.earth/ncl/geoera/keyword/332", "stylolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2386", "thesaurus"],
["https://data.geoscience.earth/ncl/geoera/keyword/533", "trial pit"],
["https://data.geoscience.earth/ncl/geoera/keyword/1172", "UNFC Code"],
["https://data.geoscience.earth/ncl/geoera/keyword/2511", "innovation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1658", "monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/2066", "geophysics"],
["https://data.geoscience.earth/ncl/geoera/keyword/2154", "evaluation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1823", "simulation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2464", "governance"],
["https://data.geoscience.earth/ncl/geoera/keyword/2178", "Quaternary"],
["https://data.geoscience.earth/ncl/geoera/keyword/1251", "extraction"],
["https://data.geoscience.earth/ncl/geoera/keyword/2125", "experiment"],
["https://data.geoscience.earth/ncl/geoera/keyword/619", "mitigation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2155", "comparison"],
["https://data.geoscience.earth/ncl/geoera/keyword/2122", "microscopy"],
["https://data.geoscience.earth/ncl/geoera/keyword/197", "deposition"],
["https://data.geoscience.earth/ncl/geoera/keyword/1374", "earthquake"],
["https://data.geoscience.earth/ncl/geoera/keyword/2069", "mineralogy"],
["https://data.geoscience.earth/ncl/geoera/keyword/1827", "statistics"],
["https://data.geoscience.earth/ncl/geoera/keyword/349", "seismology"],
["https://data.geoscience.earth/ncl/geoera/keyword/221", "subduction"],
["https://data.geoscience.earth/ncl/geoera/keyword/229", "weathering"],
["https://data.geoscience.earth/ncl/geoera/keyword/2398", "seismicity"],
["https://data.geoscience.earth/ncl/geoera/keyword/226", "fracturing"],
["https://data.geoscience.earth/ncl/geoera/keyword/212", "alteration"],
["https://data.geoscience.earth/ncl/geoera/keyword/2530", "saturation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2175", "Cretaceous"],
["https://data.geoscience.earth/ncl/geoera/keyword/240", "extinction"],
["https://data.geoscience.earth/ncl/geoera/keyword/609", "irrigation"],
["https://data.geoscience.earth/ncl/geoera/keyword/344", "gravimetry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1278", "adsorption"],
["https://data.geoscience.earth/ncl/geoera/keyword/1178", "excavation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2564", "explosions"],
["https://data.geoscience.earth/ncl/geoera/keyword/1054", "molybdenum"],
["https://data.geoscience.earth/ncl/geoera/keyword/829", "water well"],
["https://data.geoscience.earth/ncl/geoera/keyword/1002", "base metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/455", "calcareous"],
["https://data.geoscience.earth/ncl/geoera/keyword/2588", "rock falls"],
["https://data.geoscience.earth/ncl/geoera/keyword/2385", "vocabulary"],
["https://data.geoscience.earth/ncl/geoera/keyword/1487", "fatalities"],
["https://data.geoscience.earth/ncl/geoera/keyword/46", "peridotite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1711", "digitising"],
["https://data.geoscience.earth/ncl/geoera/keyword/2192", "Llandovery"],
["https://data.geoscience.earth/ncl/geoera/keyword/2168", "Ordovician"],
["https://data.geoscience.earth/ncl/geoera/keyword/770", "salt water"],
["https://data.geoscience.earth/ncl/geoera/keyword/323", "shear zone"],
["https://data.geoscience.earth/ncl/geoera/keyword/2034", "soil water"],
["https://data.geoscience.earth/ncl/geoera/keyword/1112", "epithermal"],
["https://data.geoscience.earth/ncl/geoera/keyword/2015", "pedosphere"],
["https://data.geoscience.earth/ncl/geoera/keyword/480", "semi-metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/871", "andalusite"],
["https://data.geoscience.earth/ncl/geoera/keyword/901", "carnallite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1750", "conformant"],
["https://data.geoscience.earth/ncl/geoera/keyword/2068", "glaciology"],
["https://data.geoscience.earth/ncl/geoera/keyword/852", "greenstone"],
["https://data.geoscience.earth/ncl/geoera/keyword/1088", "iron oxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/1210", "land setup"],
["https://data.geoscience.earth/ncl/geoera/keyword/2025", "soil layer"],
["https://data.geoscience.earth/ncl/geoera/keyword/99", "travertine"],
["https://data.geoscience.earth/ncl/geoera/keyword/469", "ultramafic"],
["https://data.geoscience.earth/ncl/geoera/keyword/159", "bioclastic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1852", "Caledonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/2183", "Cryogenian"],
["https://data.geoscience.earth/ncl/geoera/keyword/603", "dewatering"],
["https://data.geoscience.earth/ncl/geoera/keyword/1020", "dysprosium"],
["https://data.geoscience.earth/ncl/geoera/keyword/1023", "gadolinium"],
["https://data.geoscience.earth/ncl/geoera/keyword/47", "pyroxenite"],
["https://data.geoscience.earth/ncl/geoera/keyword/685", "salt marsh"],
["https://data.geoscience.earth/ncl/geoera/keyword/923", "serpentine"],
["https://data.geoscience.earth/ncl/geoera/keyword/2350", "supergroup"],
["https://data.geoscience.earth/ncl/geoera/keyword/2100", "environment"],
["https://data.geoscience.earth/ncl/geoera/keyword/2537", "sustainable"],
["https://data.geoscience.earth/ncl/geoera/keyword/2391", "CO2 storage"],
["https://data.geoscience.earth/ncl/geoera/keyword/2054", "hydrography"],
["https://data.geoscience.earth/ncl/geoera/keyword/755", "groundwater"],
["https://data.geoscience.earth/ncl/geoera/keyword/1767", "performance"],
["https://data.geoscience.earth/ncl/geoera/keyword/791", "temperature"],
["https://data.geoscience.earth/ncl/geoera/keyword/2105", "methodology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1102", "sedimentary"],
["https://data.geoscience.earth/ncl/geoera/keyword/2548", "stakeholder"],
["https://data.geoscience.earth/ncl/geoera/keyword/232", "dissolution"],
["https://data.geoscience.earth/ncl/geoera/keyword/1142", "agriculture"],
["https://data.geoscience.earth/ncl/geoera/keyword/2593", "instruments"],
["https://data.geoscience.earth/ncl/geoera/keyword/399", "observatory"],
["https://data.geoscience.earth/ncl/geoera/keyword/225", "deformation"],
["https://data.geoscience.earth/ncl/geoera/keyword/612", "aquaculture"],
["https://data.geoscience.earth/ncl/geoera/keyword/2132", "calibration"],
["https://data.geoscience.earth/ncl/geoera/keyword/2503", "degradation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2104", "restoration"],
["https://data.geoscience.earth/ncl/geoera/keyword/1318", "gas hydrate"],
["https://data.geoscience.earth/ncl/geoera/keyword/2468", "legislation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2106", "calculation"],
["https://data.geoscience.earth/ncl/geoera/keyword/649", "fossil fuel"],
["https://data.geoscience.earth/ncl/geoera/keyword/1324", "natural gas"],
["https://data.geoscience.earth/ncl/geoera/keyword/2076", "climatology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2052", "cartography"],
["https://data.geoscience.earth/ncl/geoera/keyword/2587", "solid earth"],
["https://data.geoscience.earth/ncl/geoera/keyword/602", "remediation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1380", "instability"],
["https://data.geoscience.earth/ncl/geoera/keyword/764", "water table"],
["https://data.geoscience.earth/ncl/geoera/keyword/2059", "geotechnics"],
["https://data.geoscience.earth/ncl/geoera/keyword/2217", "Pleistocene"],
["https://data.geoscience.earth/ncl/geoera/keyword/855", "Precambrian"],
["https://data.geoscience.earth/ncl/geoera/keyword/748", "water level"],
["https://data.geoscience.earth/ncl/geoera/keyword/2060", "volcanology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2447", "contaminant"],
["https://data.geoscience.earth/ncl/geoera/keyword/697", "river basin"],
["https://data.geoscience.earth/ncl/geoera/keyword/529", "fresh water"],
["https://data.geoscience.earth/ncl/geoera/keyword/479", "heavy metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/2495", "abstraction"],
["https://data.geoscience.earth/ncl/geoera/keyword/1275", "evaporation"],
["https://data.geoscience.earth/ncl/geoera/keyword/478", "peralkaline"],
["https://data.geoscience.earth/ncl/geoera/keyword/566", "active well"],
["https://data.geoscience.earth/ncl/geoera/keyword/1406", "hazard area"],
["https://data.geoscience.earth/ncl/geoera/keyword/713", "hydrosphere"],
["https://data.geoscience.earth/ncl/geoera/keyword/115", "phosphorite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1894", "archipelago"],
["https://data.geoscience.earth/ncl/geoera/keyword/854", "Proterozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2536", "source rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1330", "coal mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/381", "flight line"],
["https://data.geoscience.earth/ncl/geoera/keyword/1703", "informatics"],
["https://data.geoscience.earth/ncl/geoera/keyword/1081", "phosphorous"],
["https://data.geoscience.earth/ncl/geoera/keyword/766", "river water"],
["https://data.geoscience.earth/ncl/geoera/keyword/49", "carbonatite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2501", "containment"],
["https://data.geoscience.earth/ncl/geoera/keyword/2405", "flow regime"],
["https://data.geoscience.earth/ncl/geoera/keyword/147", "fault gauge"],
["https://data.geoscience.earth/ncl/geoera/keyword/1143", "fertilizers"],
["https://data.geoscience.earth/ncl/geoera/keyword/481", "metal oxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/2159", "Phanerozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2389", "terminology"],
["https://data.geoscience.earth/ncl/geoera/keyword/414", "INTERMAGNET"],
["https://data.geoscience.earth/ncl/geoera/keyword/9", "anorthosite"],
["https://data.geoscience.earth/ncl/geoera/keyword/350", "geothermics"],
["https://data.geoscience.earth/ncl/geoera/keyword/131", "amphibolite"],
["https://data.geoscience.earth/ncl/geoera/keyword/149", "cataclasite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1282", "cementation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1263", "comminution"],
["https://data.geoscience.earth/ncl/geoera/keyword/470", "ferruginous"],
["https://data.geoscience.earth/ncl/geoera/keyword/1578", "flood risks"],
["https://data.geoscience.earth/ncl/geoera/keyword/1146", "landscaping"],
["https://data.geoscience.earth/ncl/geoera/keyword/1109", "Mesoarchean"],
["https://data.geoscience.earth/ncl/geoera/keyword/915", "molybdenite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1351", "solid fuels"],
["https://data.geoscience.earth/ncl/geoera/keyword/1386", "storm surge"],
["https://data.geoscience.earth/ncl/geoera/keyword/777", "watercourse"],
["https://data.geoscience.earth/ncl/geoera/keyword/2072", "life science"],
["https://data.geoscience.earth/ncl/geoera/keyword/2061", "hydrogeology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1120", "construction"],
["https://data.geoscience.earth/ncl/geoera/keyword/1672", "conservation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1765", "availability"],
["https://data.geoscience.earth/ncl/geoera/keyword/2522", "permeability"],
["https://data.geoscience.earth/ncl/geoera/keyword/2120", "spectroscopy"],
["https://data.geoscience.earth/ncl/geoera/keyword/2598", "stratigraphy"],
["https://data.geoscience.earth/ncl/geoera/keyword/2592", "case studies"],
["https://data.geoscience.earth/ncl/geoera/keyword/2546", "cross-border"],
["https://data.geoscience.earth/ncl/geoera/keyword/345", "geomagnetism"],
["https://data.geoscience.earth/ncl/geoera/keyword/1492", "natural risk"],
["https://data.geoscience.earth/ncl/geoera/keyword/605", "water supply"],
["https://data.geoscience.earth/ncl/geoera/keyword/2388", "nomenclature"],
["https://data.geoscience.earth/ncl/geoera/keyword/582", "intermittent"],
["https://data.geoscience.earth/ncl/geoera/keyword/1761", "view service"],
["https://data.geoscience.earth/ncl/geoera/keyword/341", "fault system"],
["https://data.geoscience.earth/ncl/geoera/keyword/1286", "electrolysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/18", "igneous rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/193", "mass wasting"],
["https://data.geoscience.earth/ncl/geoera/keyword/723", "infiltration"],
["https://data.geoscience.earth/ncl/geoera/keyword/2512", "microbiology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2412", "water budget"],
["https://data.geoscience.earth/ncl/geoera/keyword/2145", "codification"],
["https://data.geoscience.earth/ncl/geoera/keyword/1753", "access point"],
["https://data.geoscience.earth/ncl/geoera/keyword/195", "wind erosion"],
["https://data.geoscience.earth/ncl/geoera/keyword/515", "radionuclide"],
["https://data.geoscience.earth/ncl/geoera/keyword/129", "serpentinite"],
["https://data.geoscience.earth/ncl/geoera/keyword/2028", "soil texture"],
["https://data.geoscience.earth/ncl/geoera/keyword/769", "inland water"],
["https://data.geoscience.earth/ncl/geoera/keyword/2041", "soil erosion"],
["https://data.geoscience.earth/ncl/geoera/keyword/314", "thrust fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/1274", "distillation"],
["https://data.geoscience.earth/ncl/geoera/keyword/718", "flood hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/384", "seismic line"],
["https://data.geoscience.earth/ncl/geoera/keyword/1645", "soil quality"],
["https://data.geoscience.earth/ncl/geoera/keyword/374", "sonar survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/439", "carbonaceous"],
["https://data.geoscience.earth/ncl/geoera/keyword/84", "conglomerate"],
["https://data.geoscience.earth/ncl/geoera/keyword/2444", "liquefaction"],
["https://data.geoscience.earth/ncl/geoera/keyword/311", "normal fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/2397", "pumping test"],
["https://data.geoscience.earth/ncl/geoera/keyword/588", "spring water"],
["https://data.geoscience.earth/ncl/geoera/keyword/839", "crushed rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1285", "incineration"],
["https://data.geoscience.earth/ncl/geoera/keyword/2151", "ISO standard"],
["https://data.geoscience.earth/ncl/geoera/keyword/1034", "praseodymium"],
["https://data.geoscience.earth/ncl/geoera/keyword/2023", "soil profile"],
["https://data.geoscience.earth/ncl/geoera/keyword/1242", "strip mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/597", "swallow hole"],
["https://data.geoscience.earth/ncl/geoera/keyword/2185", "Terreneuvian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1596", "communication"],
["https://data.geoscience.earth/ncl/geoera/keyword/2462", "vulnerability"],
["https://data.geoscience.earth/ncl/geoera/keyword/1592", "raw materials"],
["https://data.geoscience.earth/ncl/geoera/keyword/2056", "earth science"],
["https://data.geoscience.earth/ncl/geoera/keyword/1276", "precipitation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2171", "Carboniferous"],
["https://data.geoscience.earth/ncl/geoera/keyword/2071", "palaeontology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2547", "harmonization"],
["https://data.geoscience.earth/ncl/geoera/keyword/1423", "contamination"],
["https://data.geoscience.earth/ncl/geoera/keyword/2549", "best practice"],
["https://data.geoscience.earth/ncl/geoera/keyword/571", "aquifer media"],
["https://data.geoscience.earth/ncl/geoera/keyword/761", "surface water"],
["https://data.geoscience.earth/ncl/geoera/keyword/2483", "visualization"],
["https://data.geoscience.earth/ncl/geoera/keyword/2057", "sedimentology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2146", "certification"],
["https://data.geoscience.earth/ncl/geoera/keyword/2053", "geomorphology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1418", "radioactivity"],
["https://data.geoscience.earth/ncl/geoera/keyword/643", "water quality"],
["https://data.geoscience.earth/ncl/geoera/keyword/1502", "risk analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/2035", "soil moisture"],
["https://data.geoscience.earth/ncl/geoera/keyword/2544", "transboundary"],
["https://data.geoscience.earth/ncl/geoera/keyword/395", "geologic unit"],
["https://data.geoscience.earth/ncl/geoera/keyword/1156", "natural stone"],
["https://data.geoscience.earth/ncl/geoera/keyword/730", "water seepage"],
["https://data.geoscience.earth/ncl/geoera/keyword/2504", "deterioration"],
["https://data.geoscience.earth/ncl/geoera/keyword/17", "volcanic rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1181", "core drilling"],
["https://data.geoscience.earth/ncl/geoera/keyword/1145", "horticultural"],
["https://data.geoscience.earth/ncl/geoera/keyword/2489", "molasse basin"],
["https://data.geoscience.earth/ncl/geoera/keyword/2446", "seismic event"],
["https://data.geoscience.earth/ncl/geoera/keyword/2141", "soil analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/776", "thermal water"],
["https://data.geoscience.earth/ncl/geoera/keyword/765", "flowing water"],
["https://data.geoscience.earth/ncl/geoera/keyword/587", "mineral water"],
["https://data.geoscience.earth/ncl/geoera/keyword/2274", "Pliensbachian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1388", "cosmic hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/1755", "data resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/1235", "historic mine"],
["https://data.geoscience.earth/ncl/geoera/keyword/735", "ocean current"],
["https://data.geoscience.earth/ncl/geoera/keyword/4", "plutonic rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1441", "relief (land)"],
["https://data.geoscience.earth/ncl/geoera/keyword/1890", "volcanic area"],
["https://data.geoscience.earth/ncl/geoera/keyword/1291", "agglomeration"],
["https://data.geoscience.earth/ncl/geoera/keyword/1906", "beach setting"],
["https://data.geoscience.earth/ncl/geoera/keyword/771", "coastal water"],
["https://data.geoscience.earth/ncl/geoera/keyword/409", "composite log"],
["https://data.geoscience.earth/ncl/geoera/keyword/593", "cooling water"],
["https://data.geoscience.earth/ncl/geoera/keyword/1706", "expert system"],
["https://data.geoscience.earth/ncl/geoera/keyword/2485", "geostatistics"],
["https://data.geoscience.earth/ncl/geoera/keyword/432", "lead compound"],
["https://data.geoscience.earth/ncl/geoera/keyword/2199", "Mississippian"],
["https://data.geoscience.earth/ncl/geoera/keyword/2119", "reflectometry"],
["https://data.geoscience.earth/ncl/geoera/keyword/313", "reverse fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/1500", "risk exposure"],
["https://data.geoscience.earth/ncl/geoera/keyword/1473", "infrastructure"],
["https://data.geoscience.earth/ncl/geoera/keyword/1525", "climate change"],
["https://data.geoscience.earth/ncl/geoera/keyword/460", "carbon dioxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/2062", "marine geology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2124", "remote sensing"],
["https://data.geoscience.earth/ncl/geoera/keyword/1365", "natural hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/2395", "stable isotope"],
["https://data.geoscience.earth/ncl/geoera/keyword/1522", "global warming"],
["https://data.geoscience.earth/ncl/geoera/keyword/1521", "global climate"],
["https://data.geoscience.earth/ncl/geoera/keyword/585", "drinking water"],
["https://data.geoscience.earth/ncl/geoera/keyword/2525", "pharmaceutical"],
["https://data.geoscience.earth/ncl/geoera/keyword/246", "human activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2209", "Upper Jurassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2084", "water resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/1484", "protected area"],
["https://data.geoscience.earth/ncl/geoera/keyword/2116", "chromatography"],
["https://data.geoscience.earth/ncl/geoera/keyword/1554", "road transport"],
["https://data.geoscience.earth/ncl/geoera/keyword/2063", "mining geology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1003", "precious metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/651", "primary energy"],
["https://data.geoscience.earth/ncl/geoera/keyword/244", "sea level rise"],
["https://data.geoscience.earth/ncl/geoera/keyword/2498", "bioremediation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2048", "depth interval"],
["https://data.geoscience.earth/ncl/geoera/keyword/2207", "Lower Jurassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2166", "Neoproterozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/346", "paleomagnetism"],
["https://data.geoscience.earth/ncl/geoera/keyword/1693", "photogrammetry"],
["https://data.geoscience.earth/ncl/geoera/keyword/2196", "Lower Devonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/1443", "mountain range"],
["https://data.geoscience.earth/ncl/geoera/keyword/1329", "oil extraction"],
["https://data.geoscience.earth/ncl/geoera/keyword/1495", "pollution risk"],
["https://data.geoscience.earth/ncl/geoera/keyword/1234", "abandoned mine"],
["https://data.geoscience.earth/ncl/geoera/keyword/703", "alluvial plain"],
["https://data.geoscience.earth/ncl/geoera/keyword/530", "brackish water"],
["https://data.geoscience.earth/ncl/geoera/keyword/696", "catchment area"],
["https://data.geoscience.earth/ncl/geoera/keyword/347", "geoelectricity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2204", "Lower Triassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1118", "metal industry"],
["https://data.geoscience.earth/ncl/geoera/keyword/2024", "mineral matter"],
["https://data.geoscience.earth/ncl/geoera/keyword/2031", "soil condition"],
["https://data.geoscience.earth/ncl/geoera/keyword/2044", "soil mechanics"],
["https://data.geoscience.earth/ncl/geoera/keyword/2021", "soil stability"],
["https://data.geoscience.earth/ncl/geoera/keyword/2143", "water analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/2055", "natural science"],
["https://data.geoscience.earth/ncl/geoera/keyword/1207", "mineral deposit"],
["https://data.geoscience.earth/ncl/geoera/keyword/782", "energy resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/1359", "risk assessment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1497", "risk management"],
["https://data.geoscience.earth/ncl/geoera/keyword/78", "marine sediment"],
["https://data.geoscience.earth/ncl/geoera/keyword/2152", "standardisation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1712", "data processing"],
["https://data.geoscience.earth/ncl/geoera/keyword/783", "mining activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/841", "sand and gravel"],
["https://data.geoscience.earth/ncl/geoera/keyword/1280", "crystallization"],
["https://data.geoscience.earth/ncl/geoera/keyword/1430", "water pollution"],
["https://data.geoscience.earth/ncl/geoera/keyword/1708", "data protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/2514", "multiphase flow"],
["https://data.geoscience.earth/ncl/geoera/keyword/2070", "crystallography"],
["https://data.geoscience.earth/ncl/geoera/keyword/1328", "oil exploration"],
["https://data.geoscience.earth/ncl/geoera/keyword/1104", "sediment-hosted"],
["https://data.geoscience.earth/ncl/geoera/keyword/2130", "laboratory test"],
["https://data.geoscience.earth/ncl/geoera/keyword/1212", "mining district"],
["https://data.geoscience.earth/ncl/geoera/keyword/196", "coastal erosion"],
["https://data.geoscience.earth/ncl/geoera/keyword/850", "dimension stone"],
["https://data.geoscience.earth/ncl/geoera/keyword/2408", "groundwater age"],
["https://data.geoscience.earth/ncl/geoera/keyword/1240", "open pit mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/1410", "gamma radiation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1838", "lithologic unit"],
["https://data.geoscience.earth/ncl/geoera/keyword/1561", "waste treatment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1440", "erosion surface"],
["https://data.geoscience.earth/ncl/geoera/keyword/857", "industrial rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1354", "Mesoproterozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2208", "Middle Jurassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2205", "Middle Triassic"],
["https://data.geoscience.earth/ncl/geoera/keyword/210", "partial melting"],
["https://data.geoscience.earth/ncl/geoera/keyword/1378", "volcanic hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/434", "carbon monoxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/2406", "coastal aquifer"],
["https://data.geoscience.earth/ncl/geoera/keyword/1237", "deep sea mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/1135", "energy minerals"],
["https://data.geoscience.earth/ncl/geoera/keyword/1213", "excavation site"],
["https://data.geoscience.earth/ncl/geoera/keyword/1988", "forearc setting"],
["https://data.geoscience.earth/ncl/geoera/keyword/1288", "hydrometallurgy"],
["https://data.geoscience.earth/ncl/geoera/keyword/2197", "Middle Devonian"],
["https://data.geoscience.earth/ncl/geoera/keyword/486", "nitrogen oxides"],
["https://data.geoscience.earth/ncl/geoera/keyword/2020", "soil capability"],
["https://data.geoscience.earth/ncl/geoera/keyword/492", "sulphur dioxide"],
["https://data.geoscience.earth/ncl/geoera/keyword/1298", "mineral resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/2493", "characterisation"],
["https://data.geoscience.earth/ncl/geoera/keyword/653", "renewable energy"],
["https://data.geoscience.earth/ncl/geoera/keyword/1773", "geological model"],
["https://data.geoscience.earth/ncl/geoera/keyword/81", "sedimentary rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1707", "data acquisition"],
["https://data.geoscience.earth/ncl/geoera/keyword/2080", "natural resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/2418", "geothermal plays"],
["https://data.geoscience.earth/ncl/geoera/keyword/1759", "download service"],
["https://data.geoscience.earth/ncl/geoera/keyword/2156", "image processing"],
["https://data.geoscience.earth/ncl/geoera/keyword/117", "metamorphic rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1370", "seismic activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2531", "unsaturated zone"],
["https://data.geoscience.earth/ncl/geoera/keyword/999", "organic material"],
["https://data.geoscience.earth/ncl/geoera/keyword/2581", "Hydrogen storage"],
["https://data.geoscience.earth/ncl/geoera/keyword/2074", "dendrochronology"],
["https://data.geoscience.earth/ncl/geoera/keyword/2421", "open loop system"],
["https://data.geoscience.earth/ncl/geoera/keyword/2365", "pyroclastic rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/2425", "thermal capacity"],
["https://data.geoscience.earth/ncl/geoera/keyword/1317", "coal bed methane"],
["https://data.geoscience.earth/ncl/geoera/keyword/2554", "crystalline rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/714", "hydrologic cycle"],
["https://data.geoscience.earth/ncl/geoera/keyword/1433", "natural disaster"],
["https://data.geoscience.earth/ncl/geoera/keyword/1699", "water monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/2575", "Water production"],
["https://data.geoscience.earth/ncl/geoera/keyword/1637", "water protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/379", "borehole logging"],
["https://data.geoscience.earth/ncl/geoera/keyword/2126", "field experiment"],
["https://data.geoscience.earth/ncl/geoera/keyword/2210", "Lower Cretaceous"],
["https://data.geoscience.earth/ncl/geoera/keyword/552", "nitrogen content"],
["https://data.geoscience.earth/ncl/geoera/keyword/2518", "ornamental stone"],
["https://data.geoscience.earth/ncl/geoera/keyword/845", "Paleoproterozoic"],
["https://data.geoscience.earth/ncl/geoera/keyword/1704", "scientific topic"],
["https://data.geoscience.earth/ncl/geoera/keyword/2535", "solute transport"],
["https://data.geoscience.earth/ncl/geoera/keyword/1420", "background level"],
["https://data.geoscience.earth/ncl/geoera/keyword/401", "borehole purpose"],
["https://data.geoscience.earth/ncl/geoera/keyword/2469", "conceptual model"],
["https://data.geoscience.earth/ncl/geoera/keyword/312", "detachment fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/1512", "flood protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/471", "halide chemistry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1209", "mineral prospect"],
["https://data.geoscience.earth/ncl/geoera/keyword/692", "mountainous area"],
["https://data.geoscience.earth/ncl/geoera/keyword/2139", "residue analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/741", "rising sea level"],
["https://data.geoscience.earth/ncl/geoera/keyword/242", "sea level change"],
["https://data.geoscience.earth/ncl/geoera/keyword/1756", "spatial data set"],
["https://data.geoscience.earth/ncl/geoera/keyword/215", "tectonic process"],
["https://data.geoscience.earth/ncl/geoera/keyword/787", "geothermal energy"],
["https://data.geoscience.earth/ncl/geoera/keyword/2137", "chemical analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/2103", "cultural heritage"],
["https://data.geoscience.earth/ncl/geoera/keyword/792", "energy production"],
["https://data.geoscience.earth/ncl/geoera/keyword/337", "tectonic boundary"],
["https://data.geoscience.earth/ncl/geoera/keyword/1742", "geographic viewer"],
["https://data.geoscience.earth/ncl/geoera/keyword/2064", "petroleum geology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1841", "artificial ground"],
["https://data.geoscience.earth/ncl/geoera/keyword/2077", "palaeoclimatology"],
["https://data.geoscience.earth/ncl/geoera/keyword/1692", "monitoring system"],
["https://data.geoscience.earth/ncl/geoera/keyword/806", "energy conversion"],
["https://data.geoscience.earth/ncl/geoera/keyword/1474", "economic activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/1192", "feasibility study"],
["https://data.geoscience.earth/ncl/geoera/keyword/734", "ocean circulation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2110", "analytical method"],
["https://data.geoscience.earth/ncl/geoera/keyword/1462", "contaminated area"],
["https://data.geoscience.earth/ncl/geoera/keyword/2506", "ecological status"],
["https://data.geoscience.earth/ncl/geoera/keyword/2551", "geomanifestations"],
["https://data.geoscience.earth/ncl/geoera/keyword/1783", "catalogue service"],
["https://data.geoscience.earth/ncl/geoera/keyword/437", "hydrochloric acid"],
["https://data.geoscience.earth/ncl/geoera/keyword/736", "ocean temperature"],
["https://data.geoscience.earth/ncl/geoera/keyword/1390", "biological hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/501", "building material"],
["https://data.geoscience.earth/ncl/geoera/keyword/2157", "evaluation method"],
["https://data.geoscience.earth/ncl/geoera/keyword/1861", "event environment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1001", "non-ferrous metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/364", "3D seismic survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/2457", "aquatic ecosystem"],
["https://data.geoscience.earth/ncl/geoera/keyword/1103", "chemical sediment"],
["https://data.geoscience.earth/ncl/geoera/keyword/333", "deformation style"],
["https://data.geoscience.earth/ncl/geoera/keyword/1758", "discovery service"],
["https://data.geoscience.earth/ncl/geoera/keyword/499", "hydrogen sulphide"],
["https://data.geoscience.earth/ncl/geoera/keyword/183", "metamorphic grade"],
["https://data.geoscience.earth/ncl/geoera/keyword/860", "nepheline syenite"],
["https://data.geoscience.earth/ncl/geoera/keyword/1211", "non-built-up area"],
["https://data.geoscience.earth/ncl/geoera/keyword/1555", "railway transport"],
["https://data.geoscience.earth/ncl/geoera/keyword/1963", "sedimentary basin"],
["https://data.geoscience.earth/ncl/geoera/keyword/1634", "soil conservation"],
["https://data.geoscience.earth/ncl/geoera/keyword/315", "strike slip fault"],
["https://data.geoscience.earth/ncl/geoera/keyword/461", "sulfate chemistry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1403", "water endangering"],
["https://data.geoscience.earth/ncl/geoera/keyword/1782", "map access service"],
["https://data.geoscience.earth/ncl/geoera/keyword/359", "geophysical survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/1714", "environmental data"],
["https://data.geoscience.earth/ncl/geoera/keyword/1719", "information system"],
["https://data.geoscience.earth/ncl/geoera/keyword/1195", "mineral occurrence"],
["https://data.geoscience.earth/ncl/geoera/keyword/1460", "natural risk zones"],
["https://data.geoscience.earth/ncl/geoera/keyword/1698", "seismic monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/2435", "metallogenetic map"],
["https://data.geoscience.earth/ncl/geoera/keyword/1009", "rare earth element"],
["https://data.geoscience.earth/ncl/geoera/keyword/732", "sediment transport"],
["https://data.geoscience.earth/ncl/geoera/keyword/2399", "induced seismicity"],
["https://data.geoscience.earth/ncl/geoera/keyword/1246", "underground mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/869", "industrial mineral"],
["https://data.geoscience.earth/ncl/geoera/keyword/1533", "primary production"],
["https://data.geoscience.earth/ncl/geoera/keyword/1494", "environmental risk"],
["https://data.geoscience.earth/ncl/geoera/keyword/2117", "gas chromatography"],
["https://data.geoscience.earth/ncl/geoera/keyword/753", "water (geographic)"],
["https://data.geoscience.earth/ncl/geoera/keyword/998", "produced commodity"],
["https://data.geoscience.earth/ncl/geoera/keyword/1576", "climate protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/55", "basic igneous rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/68", "carbonate sediment"],
["https://data.geoscience.earth/ncl/geoera/keyword/506", "chemical substance"],
["https://data.geoscience.earth/ncl/geoera/keyword/2507", "environmental flow"],
["https://data.geoscience.earth/ncl/geoera/keyword/657", "erosional features"],
["https://data.geoscience.earth/ncl/geoera/keyword/505", "exploration result"],
["https://data.geoscience.earth/ncl/geoera/keyword/1647", "freshwater quality"],
["https://data.geoscience.earth/ncl/geoera/keyword/343", "geophysical method"],
["https://data.geoscience.earth/ncl/geoera/keyword/2407", "groundwater dating"],
["https://data.geoscience.earth/ncl/geoera/keyword/2090", "industrial product"],
["https://data.geoscience.earth/ncl/geoera/keyword/1408", "ionising radiation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1364", "pollutant exposure"],
["https://data.geoscience.earth/ncl/geoera/keyword/1696", "sampling technique"],
["https://data.geoscience.earth/ncl/geoera/keyword/2541", "territorial waters"],
["https://data.geoscience.earth/ncl/geoera/keyword/1553", "transport networks"],
["https://data.geoscience.earth/ncl/geoera/keyword/2102", "natural environment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1674", "resource management"],
["https://data.geoscience.earth/ncl/geoera/keyword/1978", "lithosphere setting"],
["https://data.geoscience.earth/ncl/geoera/keyword/1182", "resource assessment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1629", "nature conservation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2475", "numerical modelling"],
["https://data.geoscience.earth/ncl/geoera/keyword/1646", "groundwater quality"],
["https://data.geoscience.earth/ncl/geoera/keyword/334", "brittle deformation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1710", "relational database"],
["https://data.geoscience.earth/ncl/geoera/keyword/231", "chemical weathering"],
["https://data.geoscience.earth/ncl/geoera/keyword/790", "geothermal gradient"],
["https://data.geoscience.earth/ncl/geoera/keyword/2513", "microbial processes"],
["https://data.geoscience.earth/ncl/geoera/keyword/1715", "geo-referenced data"],
["https://data.geoscience.earth/ncl/geoera/keyword/457", "carbonate chemistry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1434", "geological disaster"],
["https://data.geoscience.earth/ncl/geoera/keyword/218", "continental breakup"],
["https://data.geoscience.earth/ncl/geoera/keyword/422", "detailed geophysics"],
["https://data.geoscience.earth/ncl/geoera/keyword/1510", "disaster prevention"],
["https://data.geoscience.earth/ncl/geoera/keyword/1385", "extreme temperature"],
["https://data.geoscience.earth/ncl/geoera/keyword/2085", "freshwater resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/555", "geochemical anomaly"],
["https://data.geoscience.earth/ncl/geoera/keyword/425", "geophysical anomaly"],
["https://data.geoscience.earth/ncl/geoera/keyword/1572", "heritage protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/836", "industrial material"],
["https://data.geoscience.earth/ncl/geoera/keyword/507", "inorganic substance"],
["https://data.geoscience.earth/ncl/geoera/keyword/2515", "natural attenuation"],
["https://data.geoscience.earth/ncl/geoera/keyword/420", "regional geophysics"],
["https://data.geoscience.earth/ncl/geoera/keyword/1482", "world heritage site"],
["https://data.geoscience.earth/ncl/geoera/keyword/1400", "environmental impact"],
["https://data.geoscience.earth/ncl/geoera/keyword/2413", "groundwater resource"],
["https://data.geoscience.earth/ncl/geoera/keyword/2409", "hydraulic properties"],
["https://data.geoscience.earth/ncl/geoera/keyword/428", "chemical composition"],
["https://data.geoscience.earth/ncl/geoera/keyword/2142", "statistical analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/504", "exploration activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2437", "ferromanganese crust"],
["https://data.geoscience.earth/ncl/geoera/keyword/2140", "sensitivity analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/789", "geothermal potential"],
["https://data.geoscience.earth/ncl/geoera/keyword/1514", "radiation protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/373", "seismological survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/1252", "aggregate extraction"],
["https://data.geoscience.earth/ncl/geoera/keyword/1362", "environmental hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/715", "hydrographic network"],
["https://data.geoscience.earth/ncl/geoera/keyword/1689", "monitoring technique"],
["https://data.geoscience.earth/ncl/geoera/keyword/615", "pollution monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/2434", "polymetallic nodules"],
["https://data.geoscience.earth/ncl/geoera/keyword/800", "geologic environment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1534", "mining and quarrying"],
["https://data.geoscience.earth/ncl/geoera/keyword/1697", "radiation monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/58", "sedimentary material"],
["https://data.geoscience.earth/ncl/geoera/keyword/1717", "software development"],
["https://data.geoscience.earth/ncl/geoera/keyword/1600", "water infrastructure"],
["https://data.geoscience.earth/ncl/geoera/keyword/2410", "hydraulic parameters"],
["https://data.geoscience.earth/ncl/geoera/keyword/1012", "platinum group metal"],
["https://data.geoscience.earth/ncl/geoera/keyword/2363", "pyroclastic material"],
["https://data.geoscience.earth/ncl/geoera/keyword/388", "radar interferometry"],
["https://data.geoscience.earth/ncl/geoera/keyword/784", "resource utilisation"],
["https://data.geoscience.earth/ncl/geoera/keyword/561", "detailed geochemistry"],
["https://data.geoscience.earth/ncl/geoera/keyword/1528", "climate change impact"],
["https://data.geoscience.earth/ncl/geoera/keyword/1419", "natural radioactivity"],
["https://data.geoscience.earth/ncl/geoera/keyword/2481", "temperature modelling"],
["https://data.geoscience.earth/ncl/geoera/keyword/2050", "environmental science"],
["https://data.geoscience.earth/ncl/geoera/keyword/1432", "groundwater pollution"],
["https://data.geoscience.earth/ncl/geoera/keyword/2465", "integrated management"],
["https://data.geoscience.earth/ncl/geoera/keyword/558", "regional geochemistry"],
["https://data.geoscience.earth/ncl/geoera/keyword/217", "continental collision"],
["https://data.geoscience.earth/ncl/geoera/keyword/1644", "environmental quality"],
["https://data.geoscience.earth/ncl/geoera/keyword/607", "drinking water supply"],
["https://data.geoscience.earth/ncl/geoera/keyword/1673", "land use and planning"],
["https://data.geoscience.earth/ncl/geoera/keyword/362", "3D resistivity survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/2448", "emerging contaminants"],
["https://data.geoscience.earth/ncl/geoera/keyword/2127", "laboratory experiment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1258", "resource exploitation"],
["https://data.geoscience.earth/ncl/geoera/keyword/2433", "seasonal heat storage"],
["https://data.geoscience.earth/ncl/geoera/keyword/2456", "terrestrial ecosystem"],
["https://data.geoscience.earth/ncl/geoera/keyword/2426", "thermal response test"],
["https://data.geoscience.earth/ncl/geoera/keyword/2396", "hydraulic conductivity"],
["https://data.geoscience.earth/ncl/geoera/keyword/372", "magnetotelluric survey"],
["https://data.geoscience.earth/ncl/geoera/keyword/2416", "subsurface temperature"],
["https://data.geoscience.earth/ncl/geoera/keyword/1787", "feature access service"],
["https://data.geoscience.earth/ncl/geoera/keyword/1784", "product access service"],
["https://data.geoscience.earth/ncl/geoera/keyword/2136", "environmental analysis"],
["https://data.geoscience.earth/ncl/geoera/keyword/1110", "alkaline igneous rocks"],
["https://data.geoscience.earth/ncl/geoera/keyword/153", "anthropogenic material"],
["https://data.geoscience.earth/ncl/geoera/keyword/1619", "landscape after mining"],
["https://data.geoscience.earth/ncl/geoera/keyword/545", "organic carbon content"],
["https://data.geoscience.earth/ncl/geoera/keyword/1424", "chemical contamination"],
["https://data.geoscience.earth/ncl/geoera/keyword/2101", "geophysical environment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1429", "environmental pollution"],
["https://data.geoscience.earth/ncl/geoera/keyword/1840", "lithostratigraphic unit"],
["https://data.geoscience.earth/ncl/geoera/keyword/655", "renewable energy source"],
["https://data.geoscience.earth/ncl/geoera/keyword/1786", "coverage access service"],
["https://data.geoscience.earth/ncl/geoera/keyword/1723", "decision-support system"],
["https://data.geoscience.earth/ncl/geoera/keyword/405", "geophysical measurement"],
["https://data.geoscience.earth/ncl/geoera/keyword/1404", "groundwater endangering"],
["https://data.geoscience.earth/ncl/geoera/keyword/785", "mining activity process"],
["https://data.geoscience.earth/ncl/geoera/keyword/419", "regional reconnaissance"],
["https://data.geoscience.earth/ncl/geoera/keyword/1642", "environmental assessment"],
["https://data.geoscience.earth/ncl/geoera/keyword/1643", "vulnerability assessment"],
["https://data.geoscience.earth/ncl/geoera/keyword/606", "environmental monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/1623", "environmental protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/1837", "chronostratigraphic unit"],
["https://data.geoscience.earth/ncl/geoera/keyword/2467", "managed aquifer recharge"],
["https://data.geoscience.earth/ncl/geoera/keyword/1624", "natural areas protection"],
["https://data.geoscience.earth/ncl/geoera/keyword/1259", "raw material consumption"],
["https://data.geoscience.earth/ncl/geoera/keyword/614", "water quality monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/1526", "climate change adaptation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1527", "climate change mitigation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1185", "geological interpretation"],
["https://data.geoscience.earth/ncl/geoera/keyword/1725", "environmental information"],
["https://data.geoscience.earth/ncl/geoera/keyword/1426", "radioactive contamination"],
["https://data.geoscience.earth/ncl/geoera/keyword/95", "carbonate sedimentary rock"],
["https://data.geoscience.earth/ncl/geoera/keyword/1310", "hydrocarbons (oil and gas)"],
["https://data.geoscience.earth/ncl/geoera/keyword/423", "mineral exploration result"],
["https://data.geoscience.earth/ncl/geoera/keyword/248", "structural geology elements"],
["https://data.geoscience.earth/ncl/geoera/keyword/793", "renewable energy production"],
["https://data.geoscience.earth/ncl/geoera/keyword/2438", "critical raw materials (CRM)"],
["https://data.geoscience.earth/ncl/geoera/keyword/833", "Mineral Resources (category)"],
["https://data.geoscience.earth/ncl/geoera/keyword/1125", "building and dimension stone"],
["https://data.geoscience.earth/ncl/geoera/keyword/417", "mineral exploration activity"],
["https://data.geoscience.earth/ncl/geoera/keyword/418", "detailed surface exploration"],
["https://data.geoscience.earth/ncl/geoera/keyword/613", "groundwater level monitoring"],
["https://data.geoscience.earth/ncl/geoera/keyword/1720", "geographic information system"],
["https://data.geoscience.earth/ncl/geoera/keyword/342", "Applied Geophysics (category)"],
["https://data.geoscience.earth/ncl/geoera/keyword/247", "Structural Geology (category)"],
["https://data.geoscience.earth/ncl/geoera/keyword/1401", "environmental impact of energy"],
["https://data.geoscience.earth/ncl/geoera/keyword/711", "artificial collapsed depression"],
["https://data.geoscience.earth/ncl/geoera/keyword/2414", "shallow geothermal energy (SGE)"],
["https://data.geoscience.earth/ncl/geoera/keyword/1369", "geological / hydrological hazard"],
["https://data.geoscience.earth/ncl/geoera/keyword/658", "tectonic and structural features"],
["https://data.geoscience.earth/ncl/geoera/keyword/2417", "deep geothermal energy potential"],
["https://data.geoscience.earth/ncl/geoera/keyword/1700", "environmental monitoring facilities"],
["https://data.geoscience.earth/ncl/geoera/keyword/2439", "electronic European Minerals Yearbook"],
["https://data.geoscience.earth/ncl/geoera/keyword/669", "karst and chemical weathering features"],
["https://data.geoscience.earth/ncl/geoera/keyword/1746", "model and information management service"],
["https://data.geoscience.earth/ncl/geoera/keyword/1333", "fossil fuel resources initially in place"],
["https://data.geoscience.earth/ncl/geoera/keyword/2014", "waste and material deposition area setting"],
["https://data.geoscience.earth/ncl/geoera/keyword/1114", "metasomatic replacement, hydrothermal shear, vein"]
];
